# ------------------------- #
# Don't Remove Credit 
# Owner @Mr_Mohammed_29
# ------------------------- #

services:
  - type: web
    name: md-linkshare-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: PORT
        value: 8080

# ------------------------- #
# Don't Remove Credit 
# Owner @Mr_Mohammed_29
# ------------------------- #
